* lee-weight.py
lee-weight.py is python script used to add weights according to the 2D Lee model found.

*This program modifies the root file it is run on. Make backups before you run this tool*

** Prerequisites
You must have python and root installed. lee-weight uses PyROOT Python bindings from the [[https://root.cern/][ROOT Data Analysis Framework]].

The best way to check if your install is correct is to start a python instance from your command line using

#+begin_src bash
  python
#+end_src

Then try to import the ROOT library

#+begin_src python
import ROOT
#+end_src

An error indicates that your python installation cannot see the root libraries and the script will fail.
** Usage
positional arguments:
  filename              The root file you want to reweigh.

optional arguments:
  -h, --help            show this help message and exit
  -q, --quiet           Suppress all script terminal output.
  -c CONFIG, --config CONFIG
                        Specify a configuration file.
  -v, --verbose         Turn on all debugging messages. This overrides the -q
                        option.

Users that are interested in using this tool in a script will probably want to use the quiet option to suppress all terminal output.                         
** Configuration
Use the -c option to specify a configuration file. You can many different configurations but only one file is read at a time. Use the example file provided as a template if you wish to change the weights.

At this time all weights are written to the T_eval TTree. You must edit the python script itself if you want to save your variable to a different location.

*Note the last line in "weights" is missing a comma*
This is significant. Your last line must not have a comma. Do not change the names of these options.

