* lee-weight.py
lee-weight.py is python script used to add weights according to the 2D Lee model found here
** Prerequisites
You must have python and root installed. lee-weight uses PyROOT Python bindings from the [[https://root.cern/][ROOT Data Analysis Framework]].

The best way to check if your install is correct is to start a python instance from your command line using

#+begin_src bash
  python
#+end_src

Then try to import the ROOT library

#+begin_src python
  import ROOT# Read config file
config = read_config_file("lee_2d.conf")

#+end_src

An error indicates that your python installation cannot see the root libraries and the script will fail.
** Usage
For now edit the path in root_file with the path to the root file you want to edit. This program will modify the root file so make sure you create a copy and run this on the file.
** Configuration
Edit the following line with the path to your configuration file. Use the sample configuration file provided if you want to change the weights.

*Note the last line in "weights" is missing a comma*
This is significant. Your last line must not have a comma. Do not change the names of these options.
#+begin_src python
  # Read config file
config = read_config_file("lee_2d.conf")
#+end_src

